export const GET_LEADS = 'GET_LEADS';
export const DELETE_LEAD = 'DELETE_LEAD';
export const ADD_LEAD = 'ADD_LEAD';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_START = 'REGISTER_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const ADD_COUNTRY_START = 'ADD_COUNTRY_START';
export const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS';
export const ADD_COUNTRY_ERROR = 'ADD_COUNTRY_ERROR';

export const UPDATE_COUNTRY_START = 'UPDATE_COUNTRY_START';
export const UPDATE_COUNTRY_SUCCESS = 'UPDATE_COUNTRY_SUCCESS';
export const UPDATE_COUNTRY_ERROR = 'UPDATE_COUNTRY_ERROR';

export const DELETE_COUNTRY_START = 'DELETE_COUNTRY_START';
export const DELETE_COUNTRY_SUCCESS = 'DELETE_COUNTRY_SUCCESS';
export const DELETE_COUNTRY_ERROR = 'DELETE_COUNTRY_ERROR';

export const LOAD_COUNTRY_START = 'LOAD_COUNTRY_START';
export const LOAD_COUNTRY_SUCCESS = 'LOAD_COUNTRY_SUCCESS';
export const LOAD_COUNTRY_ERROR = 'LOAD_COUNTRY_ERROR';


export const ADD_SYMPTOMS_START = 'ADD_SYMPTOMS_START';
export const ADD_SYMPTOMS_SUCCESS = 'ADD_SYMPTOMS_SUCCESS';
export const ADD_SYMPTOMS_ERROR = 'ADD_SYMPTOMS_ERROR';

export const UPDATE_SYMPTOMS_START = 'UPDATE_SYMPTOMS_START';
export const UPDATE_SYMPTOMS_SUCCESS = 'UPDATE_SYMPTOMS_SUCCESS';
export const UPDATE_SYMPTOMS_ERROR = 'UPDATE_SYMPTOMS_ERROR';

export const DELETE_SYMPTOMS_START = 'DELETE_SYMPTOMS_START';
export const DELETE_SYMPTOMS_SUCCESS = 'DELETE_SYMPTOMS_SUCCESS';
export const DELETE_SYMPTOMS_ERROR = 'DELETE_SYMPTOMS_ERROR';

export const LOAD_SYMPTOMS_START = 'LOAD_SYMPTOMS_START';
export const LOAD_SYMPTOMS_SUCCESS = 'LOAD_SYMPTOMS_SUCCESS';
export const LOAD_SYMPTOMS_ERROR = 'LOAD_SYMPTOMS_ERROR';


export const ADD_DISEASE_START = 'ADD_DISEASE_START';
export const ADD_DISEASE_SUCCESS = 'ADD_DISEASE_SUCCESS';
export const ADD_DISEASE_ERROR = 'ADD_DISEASE_ERROR';

export const UPDATE_DISEASE_START = 'UPDATE_DISEASE_START';
export const UPDATE_DISEASE_SUCCESS = 'UPDATE_DISEASE_SUCCESS';
export const UPDATE_DISEASE_ERROR = 'UPDATE_DISEASE_ERROR';

export const DELETE_DISEASE_START = 'DELETE_DISEASE_START';
export const DELETE_DISEASE_SUCCESS = 'DELETE_DISEASE_SUCCESS';
export const DELETE_DISEASE_ERROR = 'DELETE_DISEASE_ERROR';

export const LOAD_DISEASE_START = 'LOAD_DISEASE_START';
export const LOAD_DISEASE_SUCCESS = 'LOAD_DISEASE_SUCCESS';
export const LOAD_DISEASE_ERROR = 'LOAD_DISEASE_ERROR';

export const LOAD_DISEASE_SYMPTOMS_START = 'LOAD_DISEASE_SYMPTOMS_START'
export const LOAD_DISEASE_SYMPTOMS_SUCCESS = 'LOAD_DISEASE_SYMPTOMS_SUCCESS'
export const LOAD_DISEASE_SYMPTOMS_ERROR = 'LOAD_DISEASE_SYMPTOMS_ERROR'