name: .NET Core

on:
  push:
    branches: [ DEV ]
  pull_request:
    branches: [ DEV ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: |
            cd src
            cd MyHealthDb.Web
            dotnet restore
            cd ClientApp
            npm install
            cd..
            dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
